# Generated by Django 5.2.6 on 2025-09-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house', models.CharField(choices=[('G', 'Gryffindor'), ('S', 'Slytherin'), ('R', 'Ravenclaw'), ('H', 'Hufflepuff')], default='G', max_length=1)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
