# Generated by Django 5.2.6 on 2025-09-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizard',
            name='age',
        ),
        migrations.AddField(
            model_name='wizard',
            name='dateOfBirth',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wizard',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wizard',
            name='patronus',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
