# Generated by Django 5.2.6 on 2025-09-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_wizard_age_wizard_dateofbirth_wizard_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard',
            name='dateOfBirth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
