# Generated by Django 5.2.6 on 2025-09-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_wizard_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
