# Generated by Django 5.2.6 on 2025-09-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_wizard_is_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
