# Generated by Django 5.2.6 on 2025-09-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_wizard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
