# Generated by Django 5.2.6 on 2025-09-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_wizard_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood', models.CharField(choices=[('AC', 'Acacia'), ('AL', 'Alder'), ('AP', 'Apple'), ('AS', 'Ash'), ('AN', 'Aspen'), ('BE', 'Beech'), ('BT', 'Blackthorn'), ('BW', 'Black Walnut'), ('CE', 'Cedar'), ('CH', 'Cherry'), ('CS', 'Chestnut'), ('CY', 'Cypress'), ('DO', 'Dogwood'), ('EB', 'Ebony'), ('EL', 'Elm'), ('FI', 'Fir'), ('HA', 'Hawthorn'), ('HZ', 'Hazel'), ('HO', 'Holly'), ('HM', 'Hornbeam'), ('LA', 'Larch'), ('LR', 'Laurel'), ('MA', 'Maple'), ('OA', 'Oak'), ('PE', 'Pear'), ('PI', 'Pine'), ('PO', 'Poplar'), ('RD', 'Redwood'), ('RW', 'Rowan'), ('SL', 'Silver Lime'), ('SP', 'Spruce'), ('SY', 'Sycamore'), ('VI', 'Vine'), ('WA', 'Walnut'), ('WI', 'Willow'), ('YE', 'Yew')], default='AC', max_length=2)),
                ('core', models.CharField(choices=[('PF', 'Phoenix Feather'), ('DH', 'Dragon Heartstring'), ('UH', 'Unicorn Hair'), ('TT', 'Thestral Tail Hair'), ('VH', 'Veela Hair'), ('TW', 'Troll Whisker'), ('KH', 'Kelpie Hair'), ('TF', 'Thunderbird Tail Feather'), ('WC', 'Wampus Cat Hair'), ('WR', 'White River Monster Spine'), ('RH', 'Rougarou Hair'), ('HS', 'Horned Serpent Horn'), ('JA', 'Jackalope Antler'), ('BH', 'Basilisk Horn'), ('SH', 'Snallygaster Heartstring')], default='PF', max_length=2)),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.wizard')),
            ],
        ),
    ]
