# Generated by Django 5.2.6 on 2025-09-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_wand'),
    ]

    operations = [
        migrations.AddField(
            model_name='wand',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
