# Generated by Django 5.2.6 on 2025-09-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_wand_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wand',
            name='length',
            field=models.FloatField(),
        ),
    ]
