# Generated by Django 5.2.6 on 2025-09-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
