# Generated by Django 5.2.6 on 2025-09-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_spell_is_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard',
            name='spells',
            field=models.ManyToManyField(to='main_app.spell'),
        ),
    ]
